# Generated by Django 5.1.6 on 2025-02-26 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('identificacao', models.CharField(help_text='Número de identificação ou tag do animal', max_length=100, unique=True)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, null=True)),
                ('peso_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
            ],
            options={
                'db_table': 'animais',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_index=True, max_length=255, unique=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
            ],
            options={
                'db_table': 'categorias_produtos',
            },
        ),
        migrations.CreateModel(
            name='EventoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(choices=[('nascimento', 'Nascimento'), ('vacinacao', 'Vacinação'), ('engorda', 'Engorda'), ('abate', 'Abate'), ('venda', 'Venda')], max_length=50)),
                ('data_evento', models.DateField()),
                ('custo', models.DecimalField(blank=True, decimal_places=2, help_text='Custo associado a esse evento (se aplicável)', max_digits=10, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='Agro.animal')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
            ],
            options={
                'db_table': 'eventos_animais',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
            ],
            options={
                'db_table': 'fazendas',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='Agro.fazenda'),
        ),
        migrations.CreateModel(
            name='ProdutoAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, help_text='Custo médio do produto', max_digits=10)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agro.categoriaproduto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
            ],
            options={
                'db_table': 'produtos_agro',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Custo unitário na movimentação (para atualização do custo médio)', max_digits=10, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='Agro.fazenda')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro.produtoagro')),
            ],
            options={
                'db_table': 'movimentacao_estoque',
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('area', models.DecimalField(decimal_places=2, help_text='Área do talhão (pode ser em hectares ou m²)', max_digits=10)),
                ('unidade_medida', models.CharField(default='hectares', help_text='Unidade de medida da área (ex: hectares, m²)', max_length=20)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='Agro.fazenda')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
            ],
            options={
                'db_table': 'talhoes',
            },
        ),
        migrations.CreateModel(
            name='CicloFlorestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cultura', models.CharField(help_text='Tipo de cultura florestal (ex: Eucalipto, Pinus)', max_length=255)),
                ('data_plantio', models.DateField()),
                ('data_previsao_colheita', models.DateField(blank=True, null=True)),
                ('data_colheita', models.DateField(blank=True, null=True)),
                ('volume_esperado', models.DecimalField(blank=True, decimal_places=2, help_text='Volume esperado da colheita (em m³ ou outra unidade)', max_digits=10, null=True)),
                ('volume_real', models.DecimalField(blank=True, decimal_places=2, help_text='Volume efetivamente colhido', max_digits=10, null=True)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, help_text='Custo total do ciclo (produção, insumos, mão de obra, etc.)', max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_florestais', to='Agro.talhao')),
            ],
            options={
                'db_table': 'ciclos_florestais',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade_aplicada', models.DecimalField(decimal_places=2, help_text='Quantidade de insumo aplicada', max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro.produtoagro')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes_insumos', to='Agro.talhao')),
            ],
            options={
                'db_table': 'aplicacao_insumos',
            },
        ),
        migrations.CreateModel(
            name='EstoqueFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_medio_atualizado', models.DecimalField(decimal_places=2, default=0, help_text='Custo médio atualizado com base nas movimentações', max_digits=10)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizacoes', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Agro.fazenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agro.produtoagro')),
            ],
            options={
                'db_table': 'estoque_fazenda',
                'unique_together': {('fazenda', 'produto')},
            },
        ),
    ]
