# Generated by Django 5.1.6 on 2025-02-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_empresa'),
        ('companies', '0002_alter_branches_document_alter_enterprise_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='companies.branches'),
        ),
    ]
