# Generated by Django 5.1.6 on 2025-02-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_centrodecusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecusto',
            name='filho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netos', to='Financeiro.centrodecusto'),
        ),
    ]
