# Generated by Django 5.1.6 on 2025-02-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0004_rename_categorias_categoriasfinanceiro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrodecusto',
            options={'ordering': ['codigo'], 'verbose_name': 'Centro de Custo', 'verbose_name_plural': 'Centros de Custos'},
        ),
        migrations.AlterModelTable(
            name='centrodecusto',
            table='centrosdecustos',
        ),
    ]
