# Generated by Django 5.1.6 on 2025-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='document',
            field=models.CharField(max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='document',
            field=models.CharField(max_length=18, verbose_name='CPF/CNPJ'),
        ),
    ]
